# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(959, 541)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(128, 22, 491, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(710, 90, 235, 179))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 101, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(120, 20, 67, 21))
        self.label_5.setObjectName("label_5")
        self.next_button = QtWidgets.QPushButton(self.frame_2)
        self.next_button.setGeometry(QtCore.QRect(142, 52, 71, 31))
        self.next_button.setObjectName("next_button")
        self.textEdit = QtWidgets.QTextEdit(self.frame_2)
        self.textEdit.setGeometry(QtCore.QRect(20, 52, 123, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(30, 0, 121, 20))
        self.label_6.setObjectName("label_6")
        self.home_button_3 = QtWidgets.QPushButton(self.frame_2)
        self.home_button_3.setGeometry(QtCore.QRect(22, 92, 191, 31))
        self.home_button_3.setObjectName("home_button_3")
        self.begin_button_3 = QtWidgets.QPushButton(self.frame_2)
        self.begin_button_3.setGeometry(QtCore.QRect(22, 132, 191, 31))
        self.begin_button_3.setObjectName("begin_button_3")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(20, 90, 201, 179))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_11 = QtWidgets.QLabel(self.frame_4)
        self.label_11.setGeometry(QtCore.QRect(10, 30, 67, 21))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame_4)
        self.label_12.setGeometry(QtCore.QRect(10, 70, 67, 17))
        self.label_12.setObjectName("label_12")
        self.spinBox = QtWidgets.QSpinBox(self.frame_4)
        self.spinBox.setGeometry(QtCore.QRect(140, 20, 48, 31))
        self.spinBox.setObjectName("spinBox")
        self.spinBox_2 = QtWidgets.QSpinBox(self.frame_4)
        self.spinBox_2.setGeometry(QtCore.QRect(140, 60, 48, 31))
        self.spinBox_2.setObjectName("spinBox_2")
        self.label_16 = QtWidgets.QLabel(self.frame_4)
        self.label_16.setGeometry(QtCore.QRect(10, 0, 151, 20))
        self.label_16.setObjectName("label_16")
        self.begin_button = QtWidgets.QPushButton(self.frame_4)
        self.begin_button.setGeometry(QtCore.QRect(10, 100, 181, 31))
        self.begin_button.setObjectName("begin_button")
        self.home_button = QtWidgets.QPushButton(self.frame_4)
        self.home_button.setGeometry(QtCore.QRect(10, 140, 181, 31))
        self.home_button.setObjectName("home_button")
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(20, 280, 201, 171))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.textEdit_4 = QtWidgets.QTextEdit(self.frame_5)
        self.textEdit_4.setGeometry(QtCore.QRect(10, 50, 51, 31))
        self.textEdit_4.setObjectName("textEdit_4")
        self.label_14 = QtWidgets.QLabel(self.frame_5)
        self.label_14.setGeometry(QtCore.QRect(10, 30, 51, 17))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.frame_5)
        self.label_15.setGeometry(QtCore.QRect(30, 0, 141, 21))
        self.label_15.setObjectName("label_15")
        self.save_element = QtWidgets.QPushButton(self.frame_5)
        self.save_element.setGeometry(QtCore.QRect(10, 90, 181, 31))
        self.save_element.setObjectName("save_element")
        self.save_element_2 = QtWidgets.QPushButton(self.frame_5)
        self.save_element_2.setGeometry(QtCore.QRect(10, 130, 181, 31))
        self.save_element_2.setObjectName("save_element_2")
        self.label_13 = QtWidgets.QLabel(self.frame_5)
        self.label_13.setGeometry(QtCore.QRect(90, 30, 67, 17))
        self.label_13.setObjectName("label_13")
        self.textEdit_3 = QtWidgets.QTextEdit(self.frame_5)
        self.textEdit_3.setGeometry(QtCore.QRect(90, 50, 91, 31))
        self.textEdit_3.setObjectName("textEdit_3")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(674, 22, 171, 21))
        self.label_10.setObjectName("label_10")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(674, 54, 271, 21))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(880, 20, 64, 23))
        self.lcdNumber.setObjectName("lcdNumber")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(236, 90, 461, 191))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(710, 280, 239, 169))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 1, item)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(236, 290, 461, 191))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 460, 201, 25))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(710, 460, 241, 25))
        self.pushButton_3.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 959, 22))
        self.menubar.setObjectName("menubar")
        self.menuArchivo = QtWidgets.QMenu(self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNuevo = QtWidgets.QAction(MainWindow)
        self.actionNuevo.setObjectName("actionNuevo")
        self.actionGuardar = QtWidgets.QAction(MainWindow)
        self.actionGuardar.setObjectName("actionGuardar")
        self.actionGuardar_Como = QtWidgets.QAction(MainWindow)
        self.actionGuardar_Como.setObjectName("actionGuardar_Como")
        self.menuArchivo.addAction(self.actionNuevo)
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.actionGuardar)
        self.menuArchivo.addAction(self.actionGuardar_Como)
        self.menubar.addAction(self.menuArchivo.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Sistema de gestion para el conteo de puntos"))
        self.label_4.setText(_translate("MainWindow", "Coordenadas"))
        self.label_5.setText(_translate("MainWindow", "[0,0]"))
        self.next_button.setText(_translate("MainWindow", "siguiente"))
        self.label_6.setText(_translate("MainWindow", "Agregar punto"))
        self.home_button_3.setText(_translate("MainWindow", "Borrar Anterior"))
        self.begin_button_3.setText(_translate("MainWindow", "Reiniciar conteo"))
        self.label_11.setText(_translate("MainWindow", "Avance"))
        self.label_12.setText(_translate("MainWindow", "Velocidad"))
        self.label_16.setText(_translate("MainWindow", "Confi. de movimiento"))
        self.begin_button.setText(_translate("MainWindow", "Iniciar"))
        self.home_button.setText(_translate("MainWindow", "Home"))
        self.label_14.setText(_translate("MainWindow", "Letra"))
        self.label_15.setText(_translate("MainWindow", "Agregar compuesto"))
        self.save_element.setText(_translate("MainWindow", "Agregar"))
        self.save_element_2.setText(_translate("MainWindow", "reemplazar"))
        self.label_13.setText(_translate("MainWindow", "Elemento"))
        self.label_10.setText(_translate("MainWindow", "Puntos  medidos"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "01"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "02"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "03"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "04"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "05"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "06"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "07"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "08"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "09"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "10"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Componente"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Tamaño"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "moscovita_hialita"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "0.001"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "hialita"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("MainWindow", "0.05"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("MainWindow", "cuarzo"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("MainWindow", "0.07"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("MainWindow", "feldespato"))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("MainWindow", "0.01"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("MainWindow", "oro"))
        item = self.tableWidget.item(4, 1)
        item.setText(_translate("MainWindow", "0.5"))
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("MainWindow", "Gato"))
        item = self.tableWidget.item(5, 1)
        item.setText(_translate("MainWindow", "0.98"))
        item = self.tableWidget.item(6, 0)
        item.setText(_translate("MainWindow", "Perro"))
        item = self.tableWidget.item(6, 1)
        item.setText(_translate("MainWindow", "0.5"))
        item = self.tableWidget.item(7, 0)
        item.setText(_translate("MainWindow", "madera"))
        item = self.tableWidget.item(7, 1)
        item.setText(_translate("MainWindow", "0.5"))
        item = self.tableWidget.item(8, 0)
        item.setText(_translate("MainWindow", "horogenesis"))
        item = self.tableWidget.item(8, 1)
        item.setText(_translate("MainWindow", "0.6"))
        item = self.tableWidget.item(9, 0)
        item.setText(_translate("MainWindow", "movldeno"))
        item = self.tableWidget.item(9, 1)
        item.setText(_translate("MainWindow", "0.8"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton.setText(_translate("MainWindow", "Tamaños de referencia"))
        self.pushButton_3.setText(_translate("MainWindow", "Tamaños de referencia"))
        self.menuArchivo.setTitle(_translate("MainWindow", "Archivo"))
        self.actionNuevo.setText(_translate("MainWindow", "Nuevo"))
        self.actionGuardar.setText(_translate("MainWindow", "Guardar"))
        self.actionGuardar_Como.setText(_translate("MainWindow", "Guardar Como"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

