# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from funciones import *

class Ui_Gestionador(object):
    def setupUi(self, Gestionador):
        Gestionador.setObjectName("Gestionador")
        Gestionador.resize(1109, 635)
        self.centralwidget = QtWidgets.QWidget(Gestionador)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 20, 491, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(710, 150, 235, 179))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.next_button = QtWidgets.QPushButton(self.frame_2)
        self.next_button.setGeometry(QtCore.QRect(142, 52, 71, 31))
        self.next_button.setObjectName("next_button")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(70, 0, 121, 20))
        self.label_6.setObjectName("label_6")
        self.erase_last_button = QtWidgets.QPushButton(self.frame_2)
        self.erase_last_button.setGeometry(QtCore.QRect(22, 92, 191, 31))
        self.erase_last_button.setObjectName("erase_last_button")
        self.restart_counting_button = QtWidgets.QPushButton(self.frame_2)
        self.restart_counting_button.setGeometry(QtCore.QRect(22, 132, 191, 31))
        self.restart_counting_button.setObjectName("restart_counting_button")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit.setGeometry(QtCore.QRect(30, 50, 111, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(30, 128, 201, 181))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.Step_label = QtWidgets.QLabel(self.frame_4)
        self.Step_label.setGeometry(QtCore.QRect(10, 20, 67, 21))
        self.Step_label.setObjectName("Step_label")
        self.Speed_label = QtWidgets.QLabel(self.frame_4)
        self.Speed_label.setGeometry(QtCore.QRect(10, 60, 67, 17))
        self.Speed_label.setObjectName("Speed_label")
        self.Step_spinbox = QtWidgets.QSpinBox(self.frame_4)
        self.Step_spinbox.setGeometry(QtCore.QRect(140, 10, 48, 31))
        self.Step_spinbox.setObjectName("Step_spinbox")
        self.speed_spinbox = QtWidgets.QSpinBox(self.frame_4)
        self.speed_spinbox.setGeometry(QtCore.QRect(140, 50, 48, 31))
        self.speed_spinbox.setObjectName("speed_spinbox")
        self.begin_button = QtWidgets.QPushButton(self.frame_4)
        self.begin_button.setGeometry(QtCore.QRect(10, 90, 181, 31))
        self.begin_button.setObjectName("begin_button")
        self.home_button = QtWidgets.QPushButton(self.frame_4)
        self.home_button.setGeometry(QtCore.QRect(10, 130, 181, 31))
        self.home_button.setObjectName("home_button")
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(30, 350, 201, 171))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_14 = QtWidgets.QLabel(self.frame_5)
        self.label_14.setGeometry(QtCore.QRect(10, 30, 51, 17))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.frame_5)
        self.label_15.setGeometry(QtCore.QRect(30, 0, 141, 21))
        self.label_15.setObjectName("label_15")
        self.Save_element_button = QtWidgets.QPushButton(self.frame_5)
        self.Save_element_button.setGeometry(QtCore.QRect(10, 90, 181, 31))
        self.Save_element_button.setObjectName("Save_element_button")
        self.replace_element_button = QtWidgets.QPushButton(self.frame_5)
        self.replace_element_button.setGeometry(QtCore.QRect(10, 130, 181, 31))
        self.replace_element_button.setObjectName("replace_element_button")
        self.label_13 = QtWidgets.QLabel(self.frame_5)
        self.label_13.setGeometry(QtCore.QRect(90, 30, 67, 17))
        self.label_13.setObjectName("label_13")
        self.Key_input = QtWidgets.QLineEdit(self.frame_5)
        self.Key_input.setGeometry(QtCore.QRect(10, 50, 61, 25))
        self.Key_input.setObjectName("Key_input")
        self.new_compnent_input = QtWidgets.QLineEdit(self.frame_5)
        self.new_compnent_input.setGeometry(QtCore.QRect(90, 50, 91, 25))
        self.new_compnent_input.setObjectName("new_compnent_input")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(674, 22, 171, 21))
        self.label_10.setObjectName("label_10")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(674, 54, 271, 21))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(880, 20, 64, 23))
        self.lcdNumber.setObjectName("lcdNumber")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(710, 370, 241, 201))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(7)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 1, item)
        self.Size_reference_button = QtWidgets.QPushButton(self.centralwidget)
        self.Size_reference_button.setGeometry(QtCore.QRect(30, 550, 201, 25))
        self.Size_reference_button.setObjectName("Size_reference_button")
        self.graphicsView = PlotWidget(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(260, 340, 421, 231))
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView_2 = PlotWidget(self.centralwidget)
        self.graphicsView_2.setGeometry(QtCore.QRect(260, 90, 421, 231))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(720, 340, 221, 20))
        self.label_7.setObjectName("label_7")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(720, 100, 101, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(860, 100, 67, 21))
        self.label_5.setObjectName("label_5")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(50, 100, 151, 20))
        self.label_16.setObjectName("label_16")
        Gestionador.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Gestionador)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1109, 22))
        self.menubar.setObjectName("menubar")
        self.menuArchivo = QtWidgets.QMenu(self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        self.menuEditar = QtWidgets.QMenu(self.menubar)
        self.menuEditar.setObjectName("menuEditar")
        self.menuTama_o_muestra = QtWidgets.QMenu(self.menuEditar)
        self.menuTama_o_muestra.setObjectName("menuTama_o_muestra")
        self.menuAyuda = QtWidgets.QMenu(self.menubar)
        self.menuAyuda.setObjectName("menuAyuda")
        Gestionador.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Gestionador)
        self.statusbar.setObjectName("statusbar")
        Gestionador.setStatusBar(self.statusbar)
        self.actionNuevo = QtWidgets.QAction(Gestionador)
        self.actionNuevo.setObjectName("actionNuevo")
        self.actionGuardar = QtWidgets.QAction(Gestionador)
        self.actionGuardar.setObjectName("actionGuardar")
        self.actionGuardar_Como = QtWidgets.QAction(Gestionador)
        self.actionGuardar_Como.setObjectName("actionGuardar_Como")
        self.actionTutorial = QtWidgets.QAction(Gestionador)
        self.actionTutorial.setObjectName("actionTutorial")
        self.actionFAQ_s = QtWidgets.QAction(Gestionador)
        self.actionFAQ_s.setObjectName("actionFAQ_s")
        self.actionAcerca = QtWidgets.QAction(Gestionador)
        self.actionAcerca.setObjectName("actionAcerca")
        self.actionTeclado = QtWidgets.QAction(Gestionador)
        self.actionTeclado.setObjectName("actionTeclado")
        self.actionCalibrar = QtWidgets.QAction(Gestionador)
        self.actionCalibrar.setObjectName("actionCalibrar")
        self.actionInspeccionar = QtWidgets.QAction(Gestionador)
        self.actionInspeccionar.setObjectName("actionInspeccionar")
        self.actionDefecto_47x32 = QtWidgets.QAction(Gestionador)
        self.actionDefecto_47x32.setObjectName("actionDefecto_47x32")
        self.action3x3 = QtWidgets.QAction(Gestionador)
        self.action3x3.setObjectName("action3x3")
        self.action4x4 = QtWidgets.QAction(Gestionador)
        self.action4x4.setObjectName("action4x4")
        self.actionAgregar = QtWidgets.QAction(Gestionador)
        self.actionAgregar.setObjectName("actionAgregar")
        self.menuArchivo.addAction(self.actionNuevo)
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.actionGuardar)
        self.menuArchivo.addAction(self.actionGuardar_Como)
        self.menuTama_o_muestra.addSeparator()
        self.menuTama_o_muestra.addSeparator()
        self.menuTama_o_muestra.addAction(self.actionDefecto_47x32)
        self.menuTama_o_muestra.addAction(self.action3x3)
        self.menuTama_o_muestra.addAction(self.action4x4)
        self.menuTama_o_muestra.addAction(self.actionAgregar)
        self.menuEditar.addAction(self.actionTeclado)
        self.menuEditar.addAction(self.menuTama_o_muestra.menuAction())
        self.menuEditar.addAction(self.actionCalibrar)
        self.menuEditar.addAction(self.actionInspeccionar)
        self.menuAyuda.addAction(self.actionTutorial)
        self.menuAyuda.addAction(self.actionFAQ_s)
        self.menuAyuda.addAction(self.actionAcerca)
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuEditar.menuAction())
        self.menubar.addAction(self.menuAyuda.menuAction())

        self.retranslateUi(Gestionador)
        QtCore.QMetaObject.connectSlotsByName(Gestionador)


# funcion johan 
        self.begin_button.clicked.connect(self.move_init)
        self.home_button.clicked.connect(home)
        self.Save_element_button.clicked.connect(self.add_element)
        self.next_button.clicked.connect(self.save_element)
        self.erase_last_button.clicked.connect(erase) 
        self.restart_counting_button.clicked.connect(reset)
        self.Size_reference_button.clicked.connect(self.reference_pop)      
        # call when enter is presed
        self.lineEdit.returnPressed.connect(self.save_element) 
            
    def reference_pop(self):
        print('pop up with a image of size')

    def move_init(self):
    
        step_setup = self.Step_spinbox.value()
        speed_setup = self.speed_spinbox.value()
        move_setup(speed_setup,step_setup)
    
    def add_element(self):

        keys_string = self.Key_input.text()
        component_string = self.new_compnent_input.text()

        if(len(keys_string) < 4  and keys_string.isalpha() ):
            if( len(component_string) == 0 ) : 
                print('error no element ')
            else : 
                if(add_component(list(keys_string),list(component_string))):
                    self.Key_input.clear()
                    self.new_compnent_input.clear()
                else: 
                    print('error existing element or key')
        else:
            print ('error key with number or too long')

    def save_element(self):
        element_input = self.lineEdit.text() 
        self.lineEdit.clear()
        # here i have to have ecvaluete values
        add_to_list(element_input)

#end johna funcion

    def retranslateUi(self, Gestionador):
        _translate = QtCore.QCoreApplication.translate
        Gestionador.setWindowTitle(_translate("Gestionador", "Gestionador de puntos junior de barranquilla"))
        self.label.setText(_translate("Gestionador", "Sistema de gestion para el conteo de puntos"))
        self.next_button.setText(_translate("Gestionador", "siguiente"))
        self.label_6.setText(_translate("Gestionador", "Agregar punto"))
        self.erase_last_button.setText(_translate("Gestionador", "Borrar Anterior"))
        self.restart_counting_button.setText(_translate("Gestionador", "Reiniciar conteo"))
        self.Step_label.setText(_translate("Gestionador", "Avance"))
        self.Speed_label.setText(_translate("Gestionador", "Velocidad"))
        self.begin_button.setText(_translate("Gestionador", "Iniciar"))
        self.home_button.setText(_translate("Gestionador", "Home"))
        self.label_14.setText(_translate("Gestionador", "Letra(s)"))
        self.label_15.setText(_translate("Gestionador", "Agregar compuesto"))
        self.Save_element_button.setText(_translate("Gestionador", "Agregar"))
        self.replace_element_button.setText(_translate("Gestionador", "reemplazar"))
        self.label_13.setText(_translate("Gestionador", "Elemento"))
        self.label_10.setText(_translate("Gestionador", "Puntos  medidos"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Gestionador", "01"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Gestionador", "02"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Gestionador", "03"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Gestionador", "04"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Gestionador", "05"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Gestionador", "06"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("Gestionador", "07"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Gestionador", "Componente"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Gestionador", "Tamaño"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("Gestionador", "moscovita_hialita"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("Gestionador", "0.001"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("Gestionador", "hialita"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("Gestionador", "0.05"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("Gestionador", "cuarzo"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("Gestionador", "0.07"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("Gestionador", "feldespato"))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("Gestionador", "0.01"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("Gestionador", "oro"))
        item = self.tableWidget.item(4, 1)
        item.setText(_translate("Gestionador", "0.5"))
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("Gestionador", "Gato"))
        item = self.tableWidget.item(5, 1)
        item.setText(_translate("Gestionador", "0.98"))
        item = self.tableWidget.item(6, 0)
        item.setText(_translate("Gestionador", "suesca"))
        item = self.tableWidget.item(6, 1)
        item.setText(_translate("Gestionador", "1.5"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.Size_reference_button.setText(_translate("Gestionador", "Tamaños de referencia"))
        self.label_7.setText(_translate("Gestionador", "Ultimos compuestos agregados"))
        self.label_4.setText(_translate("Gestionador", "Coordenadas"))
        self.label_5.setText(_translate("Gestionador", "[0,0]"))
        self.label_16.setText(_translate("Gestionador", "Confi. de movimiento"))
        self.menuArchivo.setTitle(_translate("Gestionador", "Archivo"))
        self.menuEditar.setTitle(_translate("Gestionador", "Editar"))
        self.menuTama_o_muestra.setTitle(_translate("Gestionador", "Tamaño muestra"))
        self.menuAyuda.setTitle(_translate("Gestionador", "Ayuda"))
        self.actionNuevo.setText(_translate("Gestionador", "Nuevo"))
        self.actionGuardar.setText(_translate("Gestionador", "Guardar"))
        self.actionGuardar_Como.setText(_translate("Gestionador", "Guardar Como"))
        self.actionTutorial.setText(_translate("Gestionador", "Tutorial"))
        self.actionFAQ_s.setText(_translate("Gestionador", "FAQ\'s"))
        self.actionAcerca.setText(_translate("Gestionador", "Acerca"))
        self.actionTeclado.setText(_translate("Gestionador", "Teclado"))
        self.actionCalibrar.setText(_translate("Gestionador", "Calibrar"))
        self.actionInspeccionar.setText(_translate("Gestionador", "Inspeccionar"))
        self.actionDefecto_47x32.setText(_translate("Gestionador", "Defecto(47x32)"))
        self.action3x3.setText(_translate("Gestionador", "3x3"))
        self.action4x4.setText(_translate("Gestionador", "4x4"))
        self.actionAgregar.setText(_translate("Gestionador", "Agregar"))

from pyqtgraph import PlotWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Gestionador = QtWidgets.QMainWindow()
    ui = Ui_Gestionador()
    ui.setupUi(Gestionador)
    Gestionador.show()
    sys.exit(app.exec_())

