# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interfaz.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
        def setupUi(self, MainWindow):
                MainWindow.setObjectName("MainWindow")
                MainWindow.resize(952, 540)
                self.centralwidget = QtWidgets.QWidget(MainWindow)
                self.centralwidget.setObjectName("centralwidget")
                self.star_button = QtWidgets.QPushButton(self.centralwidget)
                self.star_button.setGeometry(QtCore.QRect(20, 100, 151, 25))
                self.star_button.setObjectName("star_button")
                self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
                self.graphicsView.setGeometry(QtCore.QRect(580, 240, 361, 221))
                self.graphicsView.setObjectName("graphicsView")
                self.graphicsView_2 = QtWidgets.QGraphicsView(self.centralwidget)
                self.graphicsView_2.setGeometry(QtCore.QRect(580, 10, 361, 221))
                self.graphicsView_2.setObjectName("graphicsView_2")
                self.lcd_count = QtWidgets.QLCDNumber(self.centralwidget)
                self.lcd_count.setGeometry(QtCore.QRect(300, 210, 61, 23))
                self.lcd_count.setObjectName("lcd_count")
                self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
                self.progressBar.setGeometry(QtCore.QRect(210, 240, 151, 23))
                self.progressBar.setProperty("value", 24)
                self.progressBar.setObjectName("progressBar")
                self.speed_spinBox = QtWidgets.QSpinBox(self.centralwidget)
                self.speed_spinBox.setGeometry(QtCore.QRect(100, 240, 48, 26))
                self.speed_spinBox.setObjectName("speed_spinBox")
                self.step_spinBox = QtWidgets.QSpinBox(self.centralwidget)
                self.step_spinBox.setGeometry(QtCore.QRect(100, 210, 48, 26))
                self.step_spinBox.setObjectName("step_spinBox")
                self.box_automatic = QtWidgets.QTextEdit(self.centralwidget)
                self.box_automatic.setGeometry(QtCore.QRect(200, 70, 171, 91))
                self.box_automatic.setObjectName("box_automatic")
                self.box_manual_setup = QtWidgets.QTextEdit(self.centralwidget)
                self.box_manual_setup.setGeometry(QtCore.QRect(10, 180, 171, 91))
                self.box_manual_setup.setObjectName("box_manual_setup")
                self.box_progress = QtWidgets.QTextEdit(self.centralwidget)
                self.box_progress.setGeometry(QtCore.QRect(200, 180, 171, 91))
                self.box_progress.setObjectName("box_progress")
                self.label_point_count = QtWidgets.QLabel(self.centralwidget)
                self.label_point_count.setGeometry(QtCore.QRect(210, 210, 67, 17))
                self.label_point_count.setObjectName("label_point_count")
                self.label_step = QtWidgets.QLabel(self.centralwidget)
                self.label_step.setGeometry(QtCore.QRect(20, 210, 67, 17))
                self.label_step.setObjectName("label_step")
                self.label_speed = QtWidgets.QLabel(self.centralwidget)
                self.label_speed.setGeometry(QtCore.QRect(20, 240, 67, 17))
                self.label_speed.setObjectName("label_speed")
                self.home_button = QtWidgets.QPushButton(self.centralwidget)
                self.home_button.setGeometry(QtCore.QRect(20, 130, 151, 25))
                self.home_button.setObjectName("home_button")
                self.box_add_element = QtWidgets.QTextEdit(self.centralwidget)
                self.box_add_element.setGeometry(QtCore.QRect(390, 70, 171, 91))
                self.box_add_element.setObjectName("box_add_element")
                self.Box_star = QtWidgets.QTextEdit(self.centralwidget)
                self.Box_star.setGeometry(QtCore.QRect(10, 70, 171, 91))
                self.Box_star.setObjectName("Box_star")
                self.Erase_last_button = QtWidgets.QPushButton(self.centralwidget)
                self.Erase_last_button.setGeometry(QtCore.QRect(400, 240, 151, 25))
                self.Erase_last_button.setObjectName("Erase_last_button")
                self.restar_counter_button = QtWidgets.QPushButton(self.centralwidget)
                self.restar_counter_button.setGeometry(QtCore.QRect(400, 210, 151, 25))
                self.restar_counter_button.setObjectName("restar_counter_button")
                self.erase_box = QtWidgets.QTextEdit(self.centralwidget)
                self.erase_box.setGeometry(QtCore.QRect(390, 180, 171, 91))
                self.erase_box.setObjectName("erase_box")
                self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
                self.tableWidget.setGeometry(QtCore.QRect(20, 291, 541, 201))
                self.tableWidget.setObjectName("tableWidget")
                self.tableWidget.setColumnCount(5)
                self.tableWidget.setRowCount(7)
                item = QtWidgets.QTableWidgetItem()
                self.tableWidget.setVerticalHeaderItem(0, item)
                item = QtWidgets.QTableWidgetItem()
                self.tableWidget.setVerticalHeaderItem(1, item)
                item = QtWidgets.QTableWidgetItem()
                self.tableWidget.setVerticalHeaderItem(2, item)
                item = QtWidgets.QTableWidgetItem()
                self.tableWidget.setVerticalHeaderItem(3, item)
                item = QtWidgets.QTableWidgetItem()
                self.tableWidget.setVerticalHeaderItem(4, item)
                item = QtWidgets.QTableWidgetItem()
                self.tableWidget.setVerticalHeaderItem(5, item)
                item = QtWidgets.QTableWidgetItem()
                self.tableWidget.setVerticalHeaderItem(6, item)
                item = QtWidgets.QTableWidgetItem()
                self.tableWidget.setHorizontalHeaderItem(0, item)
                item = QtWidgets.QTableWidgetItem()
                self.tableWidget.setHorizontalHeaderItem(1, item)
                item = QtWidgets.QTableWidgetItem()
                self.tableWidget.setHorizontalHeaderItem(2, item)
                item = QtWidgets.QTableWidgetItem()
                self.tableWidget.setHorizontalHeaderItem(3, item)
                item = QtWidgets.QTableWidgetItem()
                self.tableWidget.setHorizontalHeaderItem(4, item)
                self.Tittle = QtWidgets.QLabel(self.centralwidget)
                self.Tittle.setGeometry(QtCore.QRect(40, 20, 491, 31))
                font = QtGui.QFont()
                font.setPointSize(18)
                self.Tittle.setFont(font)
                self.Tittle.setObjectName("Tittle")
                self.add_element_button = QtWidgets.QPushButton(self.centralwidget)
                self.add_element_button.setGeometry(QtCore.QRect(400, 130, 151, 25))
                self.add_element_button.setObjectName("add_element_button")
                self.help_size_button = QtWidgets.QPushButton(self.centralwidget)
                self.help_size_button.setGeometry(QtCore.QRect(580, 470, 361, 25))
                self.help_size_button.setObjectName("help_size_button")
                self.next_element_button = QtWidgets.QPushButton(self.centralwidget)
                self.next_element_button.setGeometry(QtCore.QRect(290, 130, 71, 25))
                self.next_element_button.setObjectName("next_element_button")
                self.input_element = QtWidgets.QTextEdit(self.centralwidget)
                self.input_element.setGeometry(QtCore.QRect(210, 130, 61, 21))
                self.input_element.setObjectName("input_element")
                self.label_position = QtWidgets.QLabel(self.centralwidget)
                self.label_position.setGeometry(QtCore.QRect(210, 100, 67, 17))
                self.label_position.setObjectName("label_position")
                self.label_coordinates = QtWidgets.QLabel(self.centralwidget)
                self.label_coordinates.setGeometry(QtCore.QRect(300, 100, 61, 20))
                self.label_coordinates.setObjectName("label_coordinates")
                self.new_element = QtWidgets.QTextEdit(self.centralwidget)
                self.new_element.setGeometry(QtCore.QRect(400, 100, 71, 21))
                self.new_element.setObjectName("new_element")
                self.new_key = QtWidgets.QTextEdit(self.centralwidget)
                self.new_key.setGeometry(QtCore.QRect(480, 100, 71, 21))
                self.new_key.setObjectName("new_key")
                self.box_add_element.raise_()
                self.erase_box.raise_()
                self.Box_star.raise_()
                self.box_automatic.raise_()
                self.box_progress.raise_()
                self.box_manual_setup.raise_()
                self.star_button.raise_()
                self.graphicsView.raise_()
                self.graphicsView_2.raise_()
                self.lcd_count.raise_()
                self.progressBar.raise_()
                self.speed_spinBox.raise_()
                self.step_spinBox.raise_()
                self.label_point_count.raise_()
                self.label_step.raise_()
                self.label_speed.raise_()
                self.home_button.raise_()
                self.Erase_last_button.raise_()
                self.restar_counter_button.raise_()
                self.tableWidget.raise_()
                self.Tittle.raise_()
                self.add_element_button.raise_()
                self.help_size_button.raise_()
                self.next_element_button.raise_()
                self.input_element.raise_()
                self.label_position.raise_()
                self.label_coordinates.raise_()
                self.new_element.raise_()
                self.new_key.raise_()
                MainWindow.setCentralWidget(self.centralwidget)
                self.menubar = QtWidgets.QMenuBar(MainWindow)
                self.menubar.setGeometry(QtCore.QRect(0, 0, 952, 22))
                self.menubar.setObjectName("menubar")
                self.menuArchivo = QtWidgets.QMenu(self.menubar)
                self.menuArchivo.setObjectName("menuArchivo")
                self.menuEditar = QtWidgets.QMenu(self.menubar)
                self.menuEditar.setObjectName("menuEditar")
                self.menuModo_Operacion = QtWidgets.QMenu(self.menuEditar)
                self.menuModo_Operacion.setObjectName("menuModo_Operacion")
                self.menuTama_o = QtWidgets.QMenu(self.menuEditar)
                self.menuTama_o.setObjectName("menuTama_o")
                self.menuAyuda = QtWidgets.QMenu(self.menubar)
                self.menuAyuda.setObjectName("menuAyuda")
                MainWindow.setMenuBar(self.menubar)
                self.statusbar = QtWidgets.QStatusBar(MainWindow)
                self.statusbar.setObjectName("statusbar")
                MainWindow.setStatusBar(self.statusbar)
                self.actionNuevo = QtWidgets.QAction(MainWindow)
                self.actionNuevo.setObjectName("actionNuevo")
                self.actionGuardar = QtWidgets.QAction(MainWindow)
                self.actionGuardar.setObjectName("actionGuardar")
                self.actionExportar = QtWidgets.QAction(MainWindow)
                self.actionExportar.setObjectName("actionExportar")
                self.actionAcerca = QtWidgets.QAction(MainWindow)
                self.actionAcerca.setObjectName("actionAcerca")
                self.actionFAQ_S = QtWidgets.QAction(MainWindow)
                self.actionFAQ_S.setObjectName("actionFAQ_S")
                self.actionTutorial = QtWidgets.QAction(MainWindow)
                self.actionTutorial.setObjectName("actionTutorial")
                self.actionAcerca_2 = QtWidgets.QAction(MainWindow)
                self.actionAcerca_2.setObjectName("actionAcerca_2")
                self.actionCalibrar = QtWidgets.QAction(MainWindow)
                self.actionCalibrar.setObjectName("actionCalibrar")
                self.actionInspeccionar = QtWidgets.QAction(MainWindow)
                self.actionInspeccionar.setObjectName("actionInspeccionar")
                self.actionTeclado = QtWidgets.QAction(MainWindow)
                self.actionTeclado.setObjectName("actionTeclado")
                self.actionAutomatico = QtWidgets.QAction(MainWindow)
                self.actionAutomatico.setObjectName("actionAutomatico")
                self.actionManual = QtWidgets.QAction(MainWindow)
                self.actionManual.setObjectName("actionManual")
                self.action3x3 = QtWidgets.QAction(MainWindow)
                self.action3x3.setObjectName("action3x3")
                self.action3x4 = QtWidgets.QAction(MainWindow)
                self.action3x4.setObjectName("action3x4")
                self.action3x5 = QtWidgets.QAction(MainWindow)
                self.action3x5.setObjectName("action3x5")
                self.actionPredetermidado = QtWidgets.QAction(MainWindow)
                self.actionPredetermidado.setObjectName("actionPredetermidado")
                self.actionAgregar = QtWidgets.QAction(MainWindow)
                self.actionAgregar.setObjectName("actionAgregar")
                self.menuArchivo.addAction(self.actionNuevo)
                self.menuArchivo.addAction(self.actionGuardar)
                self.menuArchivo.addAction(self.actionExportar)
                self.menuModo_Operacion.addAction(self.actionAutomatico)
                self.menuModo_Operacion.addAction(self.actionManual)
                self.menuTama_o.addAction(self.action3x3)
                self.menuTama_o.addAction(self.action3x4)
                self.menuTama_o.addAction(self.action3x5)
                self.menuTama_o.addAction(self.actionPredetermidado)
                self.menuTama_o.addAction(self.actionAgregar)
                self.menuEditar.addAction(self.actionCalibrar)
                self.menuEditar.addAction(self.actionInspeccionar)
                self.menuEditar.addAction(self.actionTeclado)
                self.menuEditar.addAction(self.menuModo_Operacion.menuAction())
                self.menuEditar.addAction(self.menuTama_o.menuAction())
                self.menuAyuda.addAction(self.actionFAQ_S)
                self.menuAyuda.addAction(self.actionTutorial)
                self.menuAyuda.addAction(self.actionAcerca_2)
                self.menubar.addAction(self.menuArchivo.menuAction())
                self.menubar.addAction(self.menuEditar.menuAction())
                self.menubar.addAction(self.menuAyuda.menuAction())
                self.retranslateUi(MainWindow)
                QtCore.QMetaObject.connectSlotsByName(MainWindow)

                
        def retranslateUi(self, MainWindow):
                _translate = QtCore.QCoreApplication.translate
                MainWindow.setWindowTitle(_translate("MainWindow", "Contador de puntos"))
                self.star_button.setText(_translate("MainWindow", "Iniciar"))
                self.box_automatic.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                "p, li { white-space: pre-wrap; }\n"
                "</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
                "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Elemento y Tamaño</p></body></html>"))
                self.box_manual_setup.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                "p, li { white-space: pre-wrap; }\n"
                "</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
                "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Para mov manual</p></body></html>"))
                self.box_progress.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                "p, li { white-space: pre-wrap; }\n"
                "</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
                "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Progreso muestra</p>\n"
                "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
                self.label_point_count.setText(_translate("MainWindow", "puntos"))
                self.label_step.setText(_translate("MainWindow", "Paso"))
                self.label_speed.setText(_translate("MainWindow", "Velocidad"))
                self.home_button.setText(_translate("MainWindow", "Home"))
                self.box_add_element.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                "p, li { white-space: pre-wrap; }\n"
                "</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
                "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Agregar elemento</p></body></html>"))
                self.Box_star.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                "p, li { white-space: pre-wrap; }\n"
                "</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
                "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Control inicial</p>\n"
                "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
                self.Erase_last_button.setText(_translate("MainWindow", "Borrar anterior"))
                self.restar_counter_button.setText(_translate("MainWindow", "Reiniciar Conteo"))
                self.erase_box.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                "p, li { white-space: pre-wrap; }\n"
                "</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
                "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Datos </p></body></html>"))
                item = self.tableWidget.verticalHeaderItem(0)
                item.setText(_translate("MainWindow", "01"))
                item = self.tableWidget.verticalHeaderItem(1)
                item.setText(_translate("MainWindow", "2"))
                item = self.tableWidget.verticalHeaderItem(2)
                item.setText(_translate("MainWindow", "3"))
                item = self.tableWidget.verticalHeaderItem(3)
                item.setText(_translate("MainWindow", "4"))
                item = self.tableWidget.verticalHeaderItem(4)
                item.setText(_translate("MainWindow", "5"))
                item = self.tableWidget.verticalHeaderItem(5)
                item.setText(_translate("MainWindow", "6"))
                item = self.tableWidget.verticalHeaderItem(6)
                item.setText(_translate("MainWindow", "7"))
                item = self.tableWidget.horizontalHeaderItem(0)
                item.setText(_translate("MainWindow", "Num"))
                item = self.tableWidget.horizontalHeaderItem(1)
                item.setText(_translate("MainWindow", "Pos X"))
                item = self.tableWidget.horizontalHeaderItem(2)
                item.setText(_translate("MainWindow", "PosY"))
                item = self.tableWidget.horizontalHeaderItem(3)
                item.setText(_translate("MainWindow", "Elemento"))
                item = self.tableWidget.horizontalHeaderItem(4)
                item.setText(_translate("MainWindow", "Tamaño"))
                self.Tittle.setText(_translate("MainWindow", "Sistema de gestion para el conteo de puntos"))
                self.add_element_button.setText(_translate("MainWindow", "Agregar"))
                self.help_size_button.setText(_translate("MainWindow", "Tamaños de referencia"))
                self.next_element_button.setText(_translate("MainWindow", "next"))
                self.label_position.setText(_translate("MainWindow", "Posicion"))
                self.label_coordinates.setText(_translate("MainWindow", "[ x1,y1]"))
                self.menuArchivo.setTitle(_translate("MainWindow", "Archivo"))
                self.menuEditar.setTitle(_translate("MainWindow", "Editar"))
                self.menuModo_Operacion.setTitle(_translate("MainWindow", "Modo Operacion"))
                self.menuTama_o.setTitle(_translate("MainWindow", "Tamaño"))
                self.menuAyuda.setTitle(_translate("MainWindow", "Ayuda"))
                self.actionNuevo.setText(_translate("MainWindow", "Nuevo"))
                self.actionNuevo.setShortcut(_translate("MainWindow", "Ctrl+N"))
                self.actionGuardar.setText(_translate("MainWindow", "Guardar"))
                self.actionGuardar.setShortcut(_translate("MainWindow", "Ctrl+S"))
                self.actionExportar.setText(_translate("MainWindow", "Exportar"))
                self.actionExportar.setShortcut(_translate("MainWindow", "Ctrl+E"))
                self.actionAcerca.setText(_translate("MainWindow", "Acerca"))
                self.actionFAQ_S.setText(_translate("MainWindow", "FAQ\'S"))
                self.actionTutorial.setText(_translate("MainWindow", "Tutorial"))
                self.actionTutorial.setShortcut(_translate("MainWindow", "F2"))
                self.actionAcerca_2.setText(_translate("MainWindow", "Acerca"))
                self.actionCalibrar.setText(_translate("MainWindow", "Calibrar"))
                self.actionCalibrar.setShortcut(_translate("MainWindow", "Ctrl+C"))
                self.actionInspeccionar.setText(_translate("MainWindow", "Inspeccionar"))
                self.actionInspeccionar.setShortcut(_translate("MainWindow", "Ctrl+I"))
                self.actionTeclado.setText(_translate("MainWindow", "Teclado"))
                self.actionTeclado.setShortcut(_translate("MainWindow", "Ctrl+T"))
                self.actionAutomatico.setText(_translate("MainWindow", "Automatico"))
                self.actionManual.setText(_translate("MainWindow", "Manual"))
                self.action3x3.setText(_translate("MainWindow", "3x3"))
                self.action3x4.setText(_translate("MainWindow", "3x4"))
                self.action3x5.setText(_translate("MainWindow", "3x5"))
                self.actionPredetermidado.setText(_translate("MainWindow", "Predetermidado"))
                self.actionAgregar.setText(_translate("MainWindow", "Agregar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

